#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.5
#  in conjunction with Tcl version 8.6
#    Jan 17, 2023 12:00:23 PM CET  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_script = sys.argv[0]
_location = os.path.dirname(_script)

import Station_support

_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = '#d9d9d9' # X11 color: 'gray85'
_ana1color = '#d9d9d9' # X11 color: 'gray85'
_ana2color = '#ececec' # Closest X11 color: 'gray92'
_tabfg1 = 'black' 
_tabfg2 = 'black' 
_tabbg1 = 'grey75' 
_tabbg2 = 'grey89' 
_bgmode = 'light' 
font12 = "-family {Segoe UI} -size 9"
font9 = "-family {Segoe UI} -size 9"

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran:
       return
    style = ttk.Style()
    if sys.platform == "win32":
       style.theme_use('winnative')
    style.configure('.',background=_bgcolor)
    style.configure('.',foreground=_fgcolor)
    style.configure('.',font='-family {Segoe UI} -size 9')
    style.map('.',background =
       [('selected', _compcolor), ('active',_ana2color)])
    if _bgmode == 'dark':
       style.map('.',foreground =
         [('selected', 'white'), ('active','white')])
    else:
       style.map('.',foreground =
         [('selected', 'black'), ('active','black')])
    _style_code_ran = 1

class MinMaxWin:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("269x260+983+180")
        top.minsize(120, 1)
        top.maxsize(2110, 1418)
        top.resizable(1,  1)
        top.title("Min/Max Values")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        self.FramePMes = tk.LabelFrame(self.top)
        self.FramePMes.place(relx=0.0, rely=-0.115, relheight=1.558
                , relwidth=2.156)
        self.FramePMes.configure(relief='groove')
        self.FramePMes.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.FramePMes.configure(foreground="black")
        self.FramePMes.configure(text='''Mesures physiques''')
        self.FramePMes.configure(background="#d9d9d9")
        self.FramePMes.configure(highlightbackground="#d9d9d9")
        self.FramePMes.configure(highlightcolor="black")

        self.MsgPVitVent = tk.Message(self.FramePMes)
        self.MsgPVitVent.place(relx=0.017, rely=0.173, relheight=0.057
                , relwidth=0.138, bordermode='ignore')
        self.MsgPVitVent.configure(anchor='e')
        self.MsgPVitVent.configure(background="#d9d9d9")
        self.MsgPVitVent.configure(font="-family {Segoe UI} -size 9")
        self.MsgPVitVent.configure(foreground="#000000")
        self.MsgPVitVent.configure(highlightbackground="#d9d9d9")
        self.MsgPVitVent.configure(highlightcolor="black")
        self.MsgPVitVent.configure(text='''Vitesse vent''')
        self.MsgPVitVent.configure(width=80)

        self.MinVitVent = tk.Label(self.FramePMes)
        self.MinVitVent.place(relx=0.19, rely=0.173, height=21, width=64
                , bordermode='ignore')
        self.MinVitVent.configure(activebackground="#f9f9f9")
        self.MinVitVent.configure(activeforeground="black")
        self.MinVitVent.configure(background="#d9d9d9")
        self.MinVitVent.configure(disabledforeground="#a3a3a3")
        self.MinVitVent.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.MinVitVent.configure(foreground="#000000")
        self.MinVitVent.configure(highlightbackground="#d9d9d9")
        self.MinVitVent.configure(highlightcolor="black")
        self.MinVitVent.configure(text='''0''')

        self.MsgPTemperature = tk.Message(self.FramePMes)
        self.MsgPTemperature.place(relx=0.033, rely=0.272, relheight=0.057
                , relwidth=0.138, bordermode='ignore')
        self.MsgPTemperature.configure(anchor='e')
        self.MsgPTemperature.configure(background="#d9d9d9")
        self.MsgPTemperature.configure(font="-family {Segoe UI} -size 9")
        self.MsgPTemperature.configure(foreground="#000000")
        self.MsgPTemperature.configure(highlightbackground="#d9d9d9")
        self.MsgPTemperature.configure(highlightcolor="black")
        self.MsgPTemperature.configure(text='''Temperature''')
        self.MsgPTemperature.configure(width=80)

        self.MinTemperature = tk.Label(self.FramePMes)
        self.MinTemperature.place(relx=0.19, rely=0.272, height=21, width=64
                , bordermode='ignore')
        self.MinTemperature.configure(activebackground="#f9f9f9")
        self.MinTemperature.configure(activeforeground="black")
        self.MinTemperature.configure(background="#d9d9d9")
        self.MinTemperature.configure(disabledforeground="#a3a3a3")
        self.MinTemperature.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.MinTemperature.configure(foreground="#000000")
        self.MinTemperature.configure(highlightbackground="#d9d9d9")
        self.MinTemperature.configure(highlightcolor="black")
        self.MinTemperature.configure(text='''9,999 V''')

        self.MsgPLuminosite = tk.Message(self.FramePMes)
        self.MsgPLuminosite.place(relx=0.043, rely=0.37, relheight=0.054
                , relwidth=0.121, bordermode='ignore')
        self.MsgPLuminosite.configure(anchor='e')
        self.MsgPLuminosite.configure(background="#d9d9d9")
        self.MsgPLuminosite.configure(font="-family {Segoe UI} -size 9")
        self.MsgPLuminosite.configure(foreground="#000000")
        self.MsgPLuminosite.configure(highlightbackground="#d9d9d9")
        self.MsgPLuminosite.configure(highlightcolor="black")
        self.MsgPLuminosite.configure(text='''Luminosité''')
        self.MsgPLuminosite.configure(width=70)

        self.MinLuminosite = tk.Label(self.FramePMes)
        self.MinLuminosite.place(relx=0.19, rely=0.37, height=21, width=64
                , bordermode='ignore')
        self.MinLuminosite.configure(activebackground="#f9f9f9")
        self.MinLuminosite.configure(activeforeground="black")
        self.MinLuminosite.configure(background="#d9d9d9")
        self.MinLuminosite.configure(disabledforeground="#a3a3a3")
        self.MinLuminosite.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.MinLuminosite.configure(foreground="#000000")
        self.MinLuminosite.configure(highlightbackground="#d9d9d9")
        self.MinLuminosite.configure(highlightcolor="black")
        self.MinLuminosite.configure(text='''9,999 V''')

        self.MsgPHumidite = tk.Message(self.FramePMes)
        self.MsgPHumidite.place(relx=0.052, rely=0.469, relheight=0.054
                , relwidth=0.103, bordermode='ignore')
        self.MsgPHumidite.configure(anchor='e')
        self.MsgPHumidite.configure(background="#d9d9d9")
        self.MsgPHumidite.configure(font="-family {Segoe UI} -size 9")
        self.MsgPHumidite.configure(foreground="#000000")
        self.MsgPHumidite.configure(highlightbackground="#d9d9d9")
        self.MsgPHumidite.configure(highlightcolor="black")
        self.MsgPHumidite.configure(text='''Humidité''')
        self.MsgPHumidite.configure(width=60)

        self.MinHumidite = tk.Label(self.FramePMes)
        self.MinHumidite.place(relx=0.19, rely=0.469, height=21, width=64
                , bordermode='ignore')
        self.MinHumidite.configure(activebackground="#f9f9f9")
        self.MinHumidite.configure(activeforeground="black")
        self.MinHumidite.configure(background="#d9d9d9")
        self.MinHumidite.configure(disabledforeground="#a3a3a3")
        self.MinHumidite.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.MinHumidite.configure(foreground="#000000")
        self.MinHumidite.configure(highlightbackground="#d9d9d9")
        self.MinHumidite.configure(highlightcolor="black")
        self.MinHumidite.configure(text='''999 Hz''')

        self.MsgPPluviometrie = tk.Message(self.FramePMes)
        self.MsgPPluviometrie.place(relx=0.034, rely=0.568, relheight=0.054
                , relwidth=0.138, bordermode='ignore')
        self.MsgPPluviometrie.configure(anchor='e')
        self.MsgPPluviometrie.configure(background="#d9d9d9")
        self.MsgPPluviometrie.configure(font="-family {Segoe UI} -size 9")
        self.MsgPPluviometrie.configure(foreground="#000000")
        self.MsgPPluviometrie.configure(highlightbackground="#d9d9d9")
        self.MsgPPluviometrie.configure(highlightcolor="black")
        self.MsgPPluviometrie.configure(text='''Pluviomètrie''')
        self.MsgPPluviometrie.configure(width=80)

        self.MinPluviometrie = tk.Label(self.FramePMes)
        self.MinPluviometrie.place(relx=0.19, rely=0.568, height=21, width=64
                , bordermode='ignore')
        self.MinPluviometrie.configure(activebackground="#f9f9f9")
        self.MinPluviometrie.configure(activeforeground="black")
        self.MinPluviometrie.configure(background="#d9d9d9")
        self.MinPluviometrie.configure(disabledforeground="#a3a3a3")
        self.MinPluviometrie.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.MinPluviometrie.configure(foreground="#000000")
        self.MinPluviometrie.configure(highlightbackground="#d9d9d9")
        self.MinPluviometrie.configure(highlightcolor="black")
        self.MinPluviometrie.configure(text='''0''')

        _style_code()
        self.TSeparator1 = ttk.Separator(self.FramePMes)
        self.TSeparator1.place(relx=0.172, rely=0.096, relheight=0.543
                , bordermode='ignore')
        self.TSeparator1.configure(orient="vertical")

        self.TSeparator2 = ttk.Separator(self.FramePMes)
        self.TSeparator2.place(relx=0.309, rely=0.096, relheight=0.543
                , bordermode='ignore')
        self.TSeparator2.configure(orient="vertical")

        self.TSeparator3 = ttk.Separator(self.FramePMes)
        self.TSeparator3.place(relx=0.445, rely=0.096, relheight=0.543
                , bordermode='ignore')
        self.TSeparator3.configure(orient="vertical")

        self.MaxVitVent = tk.Label(self.FramePMes)
        self.MaxVitVent.place(relx=0.328, rely=0.173, height=21, width=64
                , bordermode='ignore')
        self.MaxVitVent.configure(background="#d9d9d9")
        self.MaxVitVent.configure(compound='left')
        self.MaxVitVent.configure(cursor="fleur")
        self.MaxVitVent.configure(disabledforeground="#a3a3a3")
        self.MaxVitVent.configure(font="-family {Segoe UI} -size 9")
        self.MaxVitVent.configure(foreground="#000000")
        self.MaxVitVent.configure(text='''Label''')

        self.Label1_1 = tk.Label(self.FramePMes)
        self.Label1_1.place(relx=0.248, rely=1.086, height=21, width=64
                , bordermode='ignore')
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(anchor='w')
        self.Label1_1.configure(background="#d9d9d9")
        self.Label1_1.configure(compound='left')
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font="-family {Segoe UI} -size 9")
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''Label''')

        self.MaxTemperature = tk.Label(self.FramePMes)
        self.MaxTemperature.place(relx=0.328, rely=0.272, height=21, width=64
                , bordermode='ignore')
        self.MaxTemperature.configure(activeforeground="#000000")
        self.MaxTemperature.configure(background="#d9d9d9")
        self.MaxTemperature.configure(compound='left')
        self.MaxTemperature.configure(disabledforeground="#a3a3a3")
        self.MaxTemperature.configure(font="-family {Segoe UI} -size 9")
        self.MaxTemperature.configure(foreground="#000000")
        self.MaxTemperature.configure(highlightcolor="black")
        self.MaxTemperature.configure(text='''Label''')

        self.MaxLuminosite = tk.Label(self.FramePMes)
        self.MaxLuminosite.place(relx=0.328, rely=0.37, height=21, width=64
                , bordermode='ignore')
        self.MaxLuminosite.configure(background="#d9d9d9")
        self.MaxLuminosite.configure(compound='left')
        self.MaxLuminosite.configure(disabledforeground="#a3a3a3")
        self.MaxLuminosite.configure(font="-family {Segoe UI} -size 9")
        self.MaxLuminosite.configure(foreground="#000000")
        self.MaxLuminosite.configure(text='''Label''')

        self.MaxHumidite = tk.Label(self.FramePMes)
        self.MaxHumidite.place(relx=0.328, rely=0.469, height=21, width=64
                , bordermode='ignore')
        self.MaxHumidite.configure(background="#d9d9d9")
        self.MaxHumidite.configure(compound='left')
        self.MaxHumidite.configure(disabledforeground="#a3a3a3")
        self.MaxHumidite.configure(font="-family {Segoe UI} -size 9")
        self.MaxHumidite.configure(foreground="#000000")
        self.MaxHumidite.configure(text='''Label''')

        self.MaxPluviometrie = tk.Label(self.FramePMes)
        self.MaxPluviometrie.place(relx=0.328, rely=0.568, height=21, width=64
                , bordermode='ignore')
        self.MaxPluviometrie.configure(background="#d9d9d9")
        self.MaxPluviometrie.configure(compound='left')
        self.MaxPluviometrie.configure(disabledforeground="#a3a3a3")
        self.MaxPluviometrie.configure(font="-family {Segoe UI} -size 9")
        self.MaxPluviometrie.configure(foreground="#000000")
        self.MaxPluviometrie.configure(text='''Label''')

        self.TSeparator4 = ttk.Separator(self.FramePMes)
        self.TSeparator4.place(relx=0.021, rely=0.244, relwidth=0.424
                , bordermode='ignore')

        self.TSeparator5 = ttk.Separator(self.FramePMes)
        self.TSeparator5.place(relx=0.021, rely=0.096, relheight=0.543
                , bordermode='ignore')
        self.TSeparator5.configure(orient="vertical")

        self.TSeparator6 = ttk.Separator(self.FramePMes)
        self.TSeparator6.place(relx=0.021, rely=0.343, relwidth=0.424
                , bordermode='ignore')

        self.TSeparator7 = ttk.Separator(self.FramePMes)
        self.TSeparator7.place(relx=0.021, rely=0.442, relwidth=0.424
                , bordermode='ignore')

        self.TSeparator8 = ttk.Separator(self.FramePMes)
        self.TSeparator8.place(relx=0.021, rely=0.541, relwidth=0.424
                , bordermode='ignore')

        self.TSeparator9 = ttk.Separator(self.FramePMes)
        self.TSeparator9.place(relx=0.021, rely=0.64, relwidth=0.424
                , bordermode='ignore')

        self.Message1 = tk.Message(self.FramePMes)
        self.Message1.place(relx=0.052, rely=0.099, relheight=0.047
                , relwidth=0.074, bordermode='ignore')
        self.Message1.configure(background="#d9d9d9")
        self.Message1.configure(font="-family {Segoe UI} -size 9")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(padx="1")
        self.Message1.configure(pady="1")
        self.Message1.configure(text='''Mesure''')
        self.Message1.configure(width=60)

        self.Message2 = tk.Message(self.FramePMes)
        self.Message2.place(relx=0.19, rely=0.099, relheight=0.047
                , relwidth=0.098, bordermode='ignore')
        self.Message2.configure(background="#d9d9d9")
        self.Message2.configure(font="-family {Segoe UI} -size 9")
        self.Message2.configure(foreground="#000000")
        self.Message2.configure(highlightbackground="#d9d9d9")
        self.Message2.configure(highlightcolor="black")
        self.Message2.configure(padx="1")
        self.Message2.configure(pady="1")
        self.Message2.configure(text='''Minimum''')
        self.Message2.configure(width=60)

        self.Message3 = tk.Message(self.FramePMes)
        self.Message3.place(relx=0.328, rely=0.099, relheight=0.047
                , relwidth=0.103, bordermode='ignore')
        self.Message3.configure(background="#d9d9d9")
        self.Message3.configure(font="-family {Segoe UI} -size 9")
        self.Message3.configure(foreground="#000000")
        self.Message3.configure(highlightbackground="#d9d9d9")
        self.Message3.configure(highlightcolor="black")
        self.Message3.configure(padx="1")
        self.Message3.configure(pady="1")
        self.Message3.configure(text='''Maximum''')
        self.Message3.configure(width=60)

        self.TSeparator10 = ttk.Separator(self.FramePMes)
        self.TSeparator10.place(relx=0.021, rely=0.151, relwidth=0.424
                , bordermode='ignore')

        self.TSeparator11 = ttk.Separator(self.FramePMes)
        self.TSeparator11.place(relx=0.021, rely=0.091, relwidth=0.424
                , bordermode='ignore')

        self.menubar = tk.Menu(top, font="-family {Segoe UI} -size 9", bg=_bgcolor
                ,fg='#c0c0c0')
        top.configure(menu = self.menubar)

def start_up():
    Station_support.main()

if __name__ == '__main__':
    Station_support.main()




