#############################################################################
# Generated by PAGE version 7.5
#  in conjunction with Tcl version 8.6
#  Jan 17, 2023 11:23:28 AM CET  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set desc "-family {Segoe UI} -size 9"
set vTcl(actual_gui_font_dft_desc) $desc
set vTcl(actual_gui_font_dft_name) [font create {*}$desc]
set desc "-family {Segoe UI} -size 9"
set vTcl(actual_gui_font_text_desc) $desc
set vTcl(actual_gui_font_text_name) [font create {*}$desc]
set desc "-family {Courier New} -size 10"
set vTcl(actual_gui_font_fixed_desc) $desc
set vTcl(actual_gui_font_fixed_name) [font create {*}$desc]
set desc "-family {Segoe UI} -size 9"
set vTcl(actual_gui_font_menu_desc) $desc
set vTcl(actual_gui_font_menu_name) [font create {*}$desc]
set desc "-family {Segoe UI} -size 9"
set vTcl(actual_gui_font_tooltip_desc) $desc
set vTcl(actual_gui_font_tooltip_name) [font create {*}$desc]
set desc "-family {Segoe UI} -size 9"
set vTcl(actual_gui_font_treeview_desc) $desc
set vTcl(actual_gui_font_treeview_name) [font create {*}$desc]
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1129x486+386+300
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2110 1418
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Station météo"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "MainWin" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    frame $top.fra45 \
        -borderwidth 2 -relief sunken -background $vTcl(actual_gui_bg) \
        -height 25 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 1125 
    vTcl:DefineAlias "$top.fra45" "FrameEtat" vTcl:WidgetProc "MainWin" 1
    set site_3_0 $top.fra45
    message $site_3_0.mes46 \
        -background $vTcl(actual_gui_bg) -font {-family {Segoe UI} -size 9} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {État :} -width 60 
    vTcl:DefineAlias "$site_3_0.mes46" "MsgEtat" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Mesures en cours ...} 
    vTcl:DefineAlias "$site_3_0.lab47" "Etat" vTcl:WidgetProc "MainWin" 1
    place $site_3_0.mes46 \
        -in $site_3_0 -x 3 -y 2 -width 40 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 40 -y 4 -width 468 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $top.lab66 \
        \
        -font {-family {Segoe UI} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground black -text {Mesures électriques} \
        -background $vTcl(actual_gui_bg) -height 405 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 500 
    vTcl:DefineAlias "$top.lab66" "FrameEMes" vTcl:WidgetProc "MainWin" 1
    set site_3_0 $top.lab66
    message $site_3_0.mes77 \
        -anchor e -background $vTcl(actual_gui_bg) \
        -font {-family {Segoe UI} -size 9} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Girouette -width 80 
    vTcl:DefineAlias "$site_3_0.mes77" "MsgEGirouette" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab78 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief sunken -text {9,999 V} 
    vTcl:DefineAlias "$site_3_0.lab78" "EGirouette" vTcl:WidgetProc "MainWin" 1
    message $site_3_0.mes79 \
        -anchor e -background $vTcl(actual_gui_bg) \
        -font {-family {Segoe UI} -size 9} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Anémomètre -width 80 
    vTcl:DefineAlias "$site_3_0.mes79" "MsgEAnemometre" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab81 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief sunken -text 0 
    vTcl:DefineAlias "$site_3_0.lab81" "EAnemometre" vTcl:WidgetProc "MainWin" 1
    message $site_3_0.mes82 \
        -anchor e -background $vTcl(actual_gui_bg) \
        -font {-family {Segoe UI} -size 9} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Thermomètre -width 80 
    vTcl:DefineAlias "$site_3_0.mes82" "MsgEThermometre" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab83 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief sunken -text {9,999 V} 
    vTcl:DefineAlias "$site_3_0.lab83" "EThermometre" vTcl:WidgetProc "MainWin" 1
    message $site_3_0.mes84 \
        -anchor e -background $vTcl(actual_gui_bg) \
        -font {-family {Segoe UI} -size 9} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Luxmètre -width 80 
    vTcl:DefineAlias "$site_3_0.mes84" "MsgELuxmetre" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab85 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief sunken -text {9,999 V} 
    vTcl:DefineAlias "$site_3_0.lab85" "ELuxmetre" vTcl:WidgetProc "MainWin" 1
    message $site_3_0.mes87 \
        -anchor e -background $vTcl(actual_gui_bg) \
        -font {-family {Segoe UI} -size 9} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Humidimètre -width 80 
    vTcl:DefineAlias "$site_3_0.mes87" "MsgEHumidimetre" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab88 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief sunken -text {999 Hz} 
    vTcl:DefineAlias "$site_3_0.lab88" "EHumidimetre" vTcl:WidgetProc "MainWin" 1
    message $site_3_0.mes89 \
        -anchor e -background $vTcl(actual_gui_bg) \
        -font {-family {Segoe UI} -size 9} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Pluviomètre -width 80 
    vTcl:DefineAlias "$site_3_0.mes89" "MsgEPluviometre" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab90 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief sunken -text 0 
    vTcl:DefineAlias "$site_3_0.lab90" "EPluviometre" vTcl:WidgetProc "MainWin" 1
    message $site_3_0.mes92 \
        -anchor e -background $vTcl(actual_gui_bg) \
        -font {-family {Segoe UI} -size 9} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Encodeur -width 80 
    vTcl:DefineAlias "$site_3_0.mes92" "MsgEEncodeur" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab93 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief sunken -text 0 
    vTcl:DefineAlias "$site_3_0.lab93" "EEncodeur" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab94 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief raised 
    vTcl:DefineAlias "$site_3_0.lab94" "EP1_0" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab95 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief raised 
    vTcl:DefineAlias "$site_3_0.lab95" "EP1_3" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab96 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief raised 
    vTcl:DefineAlias "$site_3_0.lab96" "EP1_2" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab97 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief raised 
    vTcl:DefineAlias "$site_3_0.lab97" "EP1_1" vTcl:WidgetProc "MainWin" 1
    message $site_3_0.mes98 \
        -anchor e -background $vTcl(actual_gui_bg) \
        -font {-family {Segoe UI} -size 9} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Durée mesures} -width 90 
    vTcl:DefineAlias "$site_3_0.mes98" "MsgEDureeMesures" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab99 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief sunken -text {9999 ms} 
    vTcl:DefineAlias "$site_3_0.lab99" "EDureeMesures" vTcl:WidgetProc "MainWin" 1
    message $site_3_0.mes102 \
        -anchor e -background $vTcl(actual_gui_bg) \
        -font {-family {Segoe UI} -size 9} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Temps de boucle rapide} -width 140 
    vTcl:DefineAlias "$site_3_0.mes102" "MsgETempsBoucleR" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab103 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief sunken -text {9999 ms} 
    vTcl:DefineAlias "$site_3_0.lab103" "ETempsBoucleR" vTcl:WidgetProc "MainWin" 1
    message $site_3_0.mes104 \
        -anchor e -background $vTcl(actual_gui_bg) \
        -font {-family {Segoe UI} -size 9} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Temps de boucle lente} -width 140 
    vTcl:DefineAlias "$site_3_0.mes104" "MsgETempsBoucleL" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab105 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief sunken -text {9999 ms} 
    vTcl:DefineAlias "$site_3_0.lab105" "ETempsBoucleL" vTcl:WidgetProc "MainWin" 1
    canvas $site_3_0.can107 \
        -background #ffffff -borderwidth 2 -closeenough 1.0 -height 143 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 253 
    vTcl:DefineAlias "$site_3_0.can107" "EChartGirouette" vTcl:WidgetProc "MainWin" 1
    canvas $site_3_0.can108 \
        -background #ffffff -borderwidth 2 -closeenough 1.0 -height 153 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 253 
    vTcl:DefineAlias "$site_3_0.can108" "EGraphHumidite" vTcl:WidgetProc "MainWin" 1
    message $site_3_0.mes109 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -font {-family {Segoe UI} -size 9} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text >>>>>> -width 61 
    vTcl:DefineAlias "$site_3_0.mes109" "Msg1" vTcl:WidgetProc "MainWin" 1
    message $site_3_0.mes110 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -font {-family {Segoe UI} -size 9} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text >>>>>> -width 61 
    vTcl:DefineAlias "$site_3_0.mes110" "Msg2" vTcl:WidgetProc "MainWin" 1
    place $site_3_0.mes77 \
        -in $site_3_0 -x 20 -y 30 -width 80 -height 22 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab78 \
        -in $site_3_0 -x 100 -y 30 -width 54 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.mes79 \
        -in $site_3_0 -x 20 -y 70 -width 80 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab81 \
        -in $site_3_0 -x 100 -y 70 -width 54 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.mes82 \
        -in $site_3_0 -x 20 -y 110 -width 80 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab83 \
        -in $site_3_0 -x 100 -y 110 -width 54 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.mes84 \
        -in $site_3_0 -x 20 -y 150 -width 80 -height 22 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab85 \
        -in $site_3_0 -x 100 -y 150 -width 54 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.mes87 \
        -in $site_3_0 -x 20 -y 190 -width 80 -height 22 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab88 \
        -in $site_3_0 -x 100 -y 190 -width 54 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.mes89 \
        -in $site_3_0 -x 20 -y 230 -width 80 -height 22 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab90 \
        -in $site_3_0 -x 100 -y 230 -width 54 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.mes92 \
        -in $site_3_0 -x 20 -y 270 -width 80 -height 22 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab93 \
        -in $site_3_0 -x 100 -y 270 -width 54 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab94 \
        -in $site_3_0 -x 185 -y 270 -width 10 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab95 \
        -in $site_3_0 -x 155 -y 270 -width 10 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab96 \
        -in $site_3_0 -x 165 -y 270 -width 10 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab97 \
        -in $site_3_0 -x 175 -y 270 -width 10 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.mes98 \
        -in $site_3_0 -x 10 -y 310 -width 90 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab99 \
        -in $site_3_0 -x 100 -y 310 -width 54 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.mes102 \
        -in $site_3_0 -x 10 -y 370 -width 140 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab103 \
        -in $site_3_0 -x 150 -y 370 -width 54 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.mes104 \
        -in $site_3_0 -x 280 -y 370 -width 140 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab105 \
        -in $site_3_0 -x 420 -y 370 -width 54 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.can107 \
        -in $site_3_0 -x 230 -y 30 -width 253 -relwidth 0 -height 143 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.can108 \
        -in $site_3_0 -x 230 -y 190 -width 253 -relwidth 0 -height 143 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.mes109 \
        -in $site_3_0 -x 160 -y 30 -width 61 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_3_0.mes110 \
        -in $site_3_0 -x 160 -y 190 -width 61 -height 23 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab47 \
        \
        -font {-family {Segoe UI} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground black -text {Mesures physiques} \
        -background $vTcl(actual_gui_bg) -height 405 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 610 
    vTcl:DefineAlias "$top.lab47" "FramePMes" vTcl:WidgetProc "MainWin" 1
    set site_3_0 $top.lab47
    message $site_3_0.mes77 \
        -anchor e -background $vTcl(actual_gui_bg) \
        -font {-family {Segoe UI} -size 9} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Direction vent} -width 80 
    vTcl:DefineAlias "$site_3_0.mes77" "MsgPDirecVent" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab78 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief sunken -text NORD-OUEST 
    vTcl:DefineAlias "$site_3_0.lab78" "PDirecVent" vTcl:WidgetProc "MainWin" 1
    message $site_3_0.mes79 \
        -anchor e -background $vTcl(actual_gui_bg) \
        -font {-family {Segoe UI} -size 9} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Vitesse vent} -width 80 
    vTcl:DefineAlias "$site_3_0.mes79" "MsgPVitVent" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab81 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief sunken -text 0 
    vTcl:DefineAlias "$site_3_0.lab81" "PVitVent" vTcl:WidgetProc "MainWin" 1
    message $site_3_0.mes82 \
        -anchor e -background $vTcl(actual_gui_bg) \
        -font {-family {Segoe UI} -size 9} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Temperature -width 80 
    vTcl:DefineAlias "$site_3_0.mes82" "MsgPTemperature" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab83 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief sunken -text {9,999 V} 
    vTcl:DefineAlias "$site_3_0.lab83" "PTemperature" vTcl:WidgetProc "MainWin" 1
    message $site_3_0.mes84 \
        -anchor e -background $vTcl(actual_gui_bg) \
        -font {-family {Segoe UI} -size 9} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Luminosité -width 80 
    vTcl:DefineAlias "$site_3_0.mes84" "MsgPLuminosite" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab85 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief sunken -text {9,999 V} 
    vTcl:DefineAlias "$site_3_0.lab85" "PLuminosite" vTcl:WidgetProc "MainWin" 1
    message $site_3_0.mes87 \
        -anchor e -background $vTcl(actual_gui_bg) \
        -font {-family {Segoe UI} -size 9} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Humidité -width 80 
    vTcl:DefineAlias "$site_3_0.mes87" "MsgPHumidite" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab88 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief sunken -text {999 Hz} 
    vTcl:DefineAlias "$site_3_0.lab88" "PHumidite" vTcl:WidgetProc "MainWin" 1
    message $site_3_0.mes89 \
        -anchor e -background $vTcl(actual_gui_bg) \
        -font {-family {Segoe UI} -size 9} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Pluviomètrie -width 80 
    vTcl:DefineAlias "$site_3_0.mes89" "MsgPPluviometrie" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab90 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief sunken -text 0 
    vTcl:DefineAlias "$site_3_0.lab90" "PPluviometrie" vTcl:WidgetProc "MainWin" 1
    message $site_3_0.mes92 \
        -anchor e -background $vTcl(actual_gui_bg) \
        -font {-family {Segoe UI} -size 9} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {N° Station} -width 80 
    vTcl:DefineAlias "$site_3_0.mes92" "MsgPNombreStation" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab93 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief sunken -text 0 
    vTcl:DefineAlias "$site_3_0.lab93" "PNombreStation" vTcl:WidgetProc "MainWin" 1
    canvas $site_3_0.can107 \
        -background #ffffff -borderwidth 2 -closeenough 1.0 -height 143 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 253 
    vTcl:DefineAlias "$site_3_0.can107" "PChartBourrasques" vTcl:WidgetProc "MainWin" 1
    ttk::progressbar $site_3_0.tPr51 \
        -length 130 -maximum 30 
    vTcl:DefineAlias "$site_3_0.tPr51" "PBVitVent" vTcl:WidgetProc "MainWin" 1
    ttk::progressbar $site_3_0.tPr53 \
        -length 130 -maximum 50 
    vTcl:DefineAlias "$site_3_0.tPr53" "PBTemperature" vTcl:WidgetProc "MainWin" 1
    ttk::progressbar $site_3_0.tPr54 \
        -length 130 -maximum 150 
    vTcl:DefineAlias "$site_3_0.tPr54" "PBLuminosite" vTcl:WidgetProc "MainWin" 1
    ttk::progressbar $site_3_0.tPr55 \
        -length 130 
    vTcl:DefineAlias "$site_3_0.tPr55" "PBHumidite" vTcl:WidgetProc "MainWin" 1
    ttk::progressbar $site_3_0.tPr56 \
        -length 130 -maximum 10 -value 2.0 
    vTcl:DefineAlias "$site_3_0.tPr56" "PBPluviometrie" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab58 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 0 
    vTcl:DefineAlias "$site_3_0.lab58" "Label1" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab59 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 0 
    vTcl:DefineAlias "$site_3_0.lab59" "Label1_1" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab60 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 0 
    vTcl:DefineAlias "$site_3_0.lab60" "Label2" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab61 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 0 
    vTcl:DefineAlias "$site_3_0.lab61" "Label3" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab62 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 0 
    vTcl:DefineAlias "$site_3_0.lab62" "Label4" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab63 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -borderwidth 0 \
        -compound left -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 0 
    vTcl:DefineAlias "$site_3_0.lab63" "Label5" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab64 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 30 
    vTcl:DefineAlias "$site_3_0.lab64" "Label6" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab65 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 50 
    vTcl:DefineAlias "$site_3_0.lab65" "Label7" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab66 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 150 
    vTcl:DefineAlias "$site_3_0.lab66" "Label8" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab67 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 100 
    vTcl:DefineAlias "$site_3_0.lab67" "Label9" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab68 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 10 
    vTcl:DefineAlias "$site_3_0.lab68" "Label10" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text Texte 
    vTcl:DefineAlias "$site_3_0.lab46" "PTexteBourrasques" vTcl:WidgetProc "MainWin" 1
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief sunken -text 0 
    vTcl:DefineAlias "$site_3_0.lab47" "PNombreStation_1" vTcl:WidgetProc "MainWin" 1
    place $site_3_0.mes77 \
        -in $site_3_0 -x 20 -y 30 -width 80 -height 22 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab78 \
        -in $site_3_0 -x 100 -y 30 -width 84 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.mes79 \
        -in $site_3_0 -x 20 -y 70 -width 80 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab81 \
        -in $site_3_0 -x 100 -y 70 -width 84 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.mes82 \
        -in $site_3_0 -x 20 -y 110 -width 80 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab83 \
        -in $site_3_0 -x 100 -y 110 -width 84 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.mes84 \
        -in $site_3_0 -x 20 -y 150 -width 80 -height 22 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab85 \
        -in $site_3_0 -x 100 -y 150 -width 84 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.mes87 \
        -in $site_3_0 -x 20 -y 190 -width 80 -height 22 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab88 \
        -in $site_3_0 -x 100 -y 190 -width 84 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.mes89 \
        -in $site_3_0 -x 20 -y 230 -width 80 -height 22 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab90 \
        -in $site_3_0 -x 100 -y 230 -width 84 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.mes92 \
        -in $site_3_0 -x 20 -y 270 -width 80 -height 22 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab93 \
        -in $site_3_0 -x 100 -y 270 -width 34 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.can107 \
        -in $site_3_0 -x 340 -y 60 -width 253 -relwidth 0 -height 143 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tPr51 \
        -in $site_3_0 -x 190 -y 70 -width 130 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tPr53 \
        -in $site_3_0 -x 190 -y 110 -width 130 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tPr54 \
        -in $site_3_0 -x 190 -y 150 -width 130 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tPr55 \
        -in $site_3_0 -x 190 -y 190 -width 130 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tPr56 \
        -in $site_3_0 -x 190 -y 230 -width 130 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab58 \
        -in $site_3_0 -x 190 -y 94 -width 12 -relwidth 0 -height 15 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab59 \
        -in $site_3_0 -x 692 -y 7 -width 12 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 190 -y 135 -width 8 -relwidth 0 -height 15 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 190 -y 175 -width 12 -relwidth 0 -height 15 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab62 \
        -in $site_3_0 -x 190 -y 215 -width 8 -relwidth 0 -height 15 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 190 -y 53 -width 9 -relwidth 0 -height 15 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab64 \
        -in $site_3_0 -x 303 -y 53 -width 14 -relwidth 0 -height 15 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab65 \
        -in $site_3_0 -x 303 -y 93 -width 14 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 300 -y 135 -width 20 -relwidth 0 -height 15 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab67 \
        -in $site_3_0 -x 300 -y 175 -width 20 -relwidth 0 -height 15 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 304 -y 215 -width 14 -relwidth 0 -height 15 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 340 -y 210 -width 254 -relwidth 0 -height 181 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 833 -y 427 -width 54 -height 21 -anchor nw \
        -bordermode ignore 
    message $top.mes49 \
        -anchor e -background $vTcl(actual_gui_bg) \
        -font {-family {Segoe UI} -size 9} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Détection bourrasques} -width 130 
    vTcl:DefineAlias "$top.mes49" "MsgBourrasques" vTcl:WidgetProc "MainWin" 1
    button $top.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background #c0c0c0 -compound left -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground #ff0000 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Reset Measurements} 
    vTcl:DefineAlias "$top.but46" "ResetButton" vTcl:WidgetProc "MainWin" 1
    bind $top.but46 <ButtonRelease-1> {
        lambda e: BtnPlvResetEvt(e)
    }
    button $top.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background #c0c0c0 -compound left -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Min/Max Values} 
    vTcl:DefineAlias "$top.but47" "InitializeButton" vTcl:WidgetProc "MainWin" 1
    bind $top.but47 <ButtonRelease-1> {
        lambda e: BtnMinMaxEvt(e)
    }
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra45 \
        -in $top -x 0 -y 460 -width 1125 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab66 \
        -in $top -x 10 -y 10 -width 500 -relwidth 0 -height 405 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 510 -y 10 -width 610 -relwidth 0 -height 405 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.mes49 \
        -in $top -x 910 -y 50 -width 130 -relwidth 0 -height 22 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 990 -y 420 -width 127 -relwidth 0 -height 34 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 850 -y 420 -width 127 -relwidth 0 -height 34 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

